app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_extra:
    resource: .
    type: extra
    prefix: admin

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin
        permanent: true